config/routes.rb
Rails.application.routes.draw do
  root 'tasks#index'
  resources :users
  resources :tasks
  get    '/login'  => 'sessions#new'
  post   '/login'  => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  resources :subscriptions, only: [:create]
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :user
  belongs_to :task
end

app/models/task.rb
class Task < ActiveRecord::Base
  has_many :subscriptions
  has_many :users, through: :subscriptions
  validates_presence_of :name, :description, :user_id, :state

  def subscriber?(user)
    self.users.include?(user)
  end

  def update_subscribers
    self.users.each do |user|
      SubscriptionMailer.task_update(user, self).deliver_later
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :subscriptions
  has_many :tasks, through: :subscriptions
  before_save :downcase_user_fields

  validates :username, presence: true,
    length: { minimum: 5, maximum: 32 },
    uniqueness: { case_sensitive: false }

  # Hat tip to Michael Hartl's Rails Tutorial
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
    format: { with: VALID_EMAIL_REGEX },
    uniqueness: { case_sensitive: false }

  has_secure_password

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
      BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def downcase_user_fields
    self.username = username.downcase
    self.email    = email.downcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper
  include TasksHelper
  
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      log_in user
      flash[:success] = 'Successfully logged in!'
      redirect_back_or root_path
    else
      flash.now[:danger] = 'Invalid email/password combination!'
      render 'new'
    end
  end

  def destroy
    log_out
    flash[:info] = 'Successfully logged out.'
    redirect_to root_url
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :logged_in_user, only: [:create]

  def create
    subscription = Subscription.new(subscription_params)
    if correct_user(subscription)
      if subscription.save
        flash[:success] = "Successfully subscribed to task updates!"
      else
        flash[:danger] = "Subscription failed to save!"
      end
    else
      flash[:danger] = "User doesn't match!"
    end
    redirect_to task_path(subscription.task_id)
  end

  private
  def subscription_params
    params.require(:subscription).permit(:user_id, :task_id)
  end

  def correct_user(subscription)
    current_user.id == subscription.user_id
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :logged_in_user, only: [:new, :create, :update]

  VALID_TASK_STATES = ["TODO", "WIP", "DONE", "CANCELED"]

  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    new_task_params = task_params
    new_task_params["user_id"] = created_by_user
    new_task_params["state"] = VALID_TASK_STATES.first
    @task = Task.new(new_task_params)
    if @task.save
      redirect_to @task
    else
      render :new
    end
  end

  def update
    task = Task.find(params[:id])
    send_update_email = true if new_state?(task, task_update_params)
    if task.update_attributes(task_update_params)
      if send_update_email
        task.update_subscribers
      end
      flash[:success] = "Task Updated"
      redirect_to task
    else
      render task
    end
  end

  def show
    @task = Task.find(params[:id])
    @created_by_user = User.find(@task.user_id)
    @valid_states = VALID_TASK_STATES
    if logged_in? && !@task.subscriber?(current_user)
      @subscription = Subscription.new(
        user_id: current_user.id,
        task_id: @task.id
      )
    end
  end

  private
  def task_params
    params.require(:task)
      .permit(:name, :description)
  end

  def task_update_params
    params.require(:task)
      .permit(:name, :description, :state)
  end

  def created_by_user
    current_user.id
  end

  def new_state?(task, params)
    if params["state"] && params["state"] != task.state
      true
    else
      false
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "User created successfully!"
      redirect_to @user
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user)
      .permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.url if request.get?
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
  def badge_for(task, prefix)
    case task.state
    when "TODO"
      prefix + "warning"
    when "WIP"
      prefix + "info"
    when "DONE"
      prefix + "success"
    when "CANCELED"
      prefix + "danger"
    else
      ""
    end
  end
end

app/views/layouts/_header.html.erb
<header class="navbar">
  <div class="container-fluid">
    <ul class="nav navbar-nav">
      <li><%= link_to 'Home', root_path %></li>
      <% if logged_in? %>
        <li><%= link_to 'Log Out', logout_path, method: :delete %></li>
      <% else %>
        <li><%= link_to 'Log In', login_path %></li>
        <li><%= link_to 'Register', new_user_path %></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>

    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>

  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/tasks/index.html.erb
<h2>Tasks</h2>

<ul class="list-group">
  <% @tasks.each do |task| %>
    <%= link_to task_path(task) do %>
      <li class="list-group-item <%= badge_for(task, "list-group-item-") %>">
        <%= task.name %>
      </li>
    <% end %>
  <% end %>
</ul>

<%= link_to 'Create New Task', new_task_path, class: "btn btn-info" %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= form_for(@task) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :description %>
  <%= f.text_field :description, class: 'form-control' %>

  <%= f.submit "Create Task" %>
<% end %>

app/views/tasks/show.html.erb
<h2><%= @task.name %></h2>

<span class="label <%= badge_for(@task, "label-") %>"><%= @task.state %></span>

<p><%= @task.description %></p>

<p>Created By: <%= @created_by_user.username %></p>

<% if logged_in? %>
  <%= form_for(@task, html: {class: "form-inline"}) do |f| %>
    <%= f.select(:state) do %>
      <% @valid_states.each do |c| %>
        <%= content_tag(:option, c, value: c) %>
      <% end %>
    <% end %>
    <%= f.submit 'Change Task State' %>
  <% end %>
  <% if @subscription %>
    <%= form_for(@subscription) do |f| %>
      <%= f.hidden_field :user_id, value: @subscription.user_id %>
      <%= f.hidden_field :task_id, value: @subscription.task_id %>
      <%= f.submit 'Subscribe to Task Updates' %>
    <% end %>
  <% end %>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :username %>
  <%= f.text_field :username, class: "form-control" %>

  <%= f.label :email %>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label :password %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation, "Confirmation" %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <%= f.submit "Create", class: "btn btn-default" %>
<% end %>

app/views/users/show.html.erb
<h2><%= @user.username %></h2>

<% unless @user.tasks.empty? %>
  <% @user.tasks.each do |task| %>
    <p>Subscribed To: <%= task.name %><p>
  <% end %>
<% end %>